name: ${project.name}
version: ${project.version}
main: kr.kro.minestar.minefarm.Main
api-version: 1.17
authors: [ MineStar ]
commands:
  is:
    aliases: [ farm, 팜 ]
    permission: minestar.tutoial
    permission-message: §c권한이 없습니다.